"""add role column to User model

Revision ID: 6b66eefd6c7f
Revises: bd21f1455171
Create Date: 2025-11-09 09:23:09.412511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b66eefd6c7f'
down_revision = 'bd21f1455171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('ADMINISTRATOR', 'CURATOR', 'USER', 'GUEST', name='roletype'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    op.drop_table('webhook')
    # ### end Alembic commands ###
