"""Add enabled_two_factor to UserProfile

Revision ID: 8d8bbb8b17bf
Revises: a8b3fa9ca008
Create Date: 2025-11-14 13:05:49.389548

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d8bbb8b17bf'
down_revision = 'a8b3fa9ca008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled_two_factor', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('enabled_two_factor')

    # ### end Alembic commands ###
