"""new_data_and_dwl_count

Revision ID: 9ad3d3f5360b
Revises: bd21f1455171
Create Date: 2025-11-09 21:09:32.398083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad3d3f5360b'
down_revision = 'bd21f1455171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('download_counter', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.drop_column('download_counter')

    # ### end Alembic commands ###
